sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-636.pdf --upload --lsstdoc LDM-636.tex --env=travis --ltd-product ldm-636"
env:
  global:
    # LSST the Docs credentials
    - secure: "KxQyD4sXqjYzBUwwS06R0KwJ3EGvh4Ukxp4NoH+D6NuclJ9CdScDdvya4YrhNyW/P7tsTLeD1ocph0Iz4CCt2TrHyOoA9w74AfK+ZS7ZtlkHxuBOH2ECc2dTNRPgVIuxwJ10HQ8Ly+zJho+6XMonyJyCR44bjpHMrOA/FGrrFPKSWGZXRdUx9EKW0bVVpUO9FyxcDEH5HodMyZxJZR4V66LsLx48Qo/VdSqZTtQ0fiVDlCWSNimTI8f/uH0HZzNdcB5fYgBQI45o7+E5rT5kMbmzYgSaDxUTPs0LiAQ/7OmhJqk89z3bJMh74wp7W4AUpzOYX90ruAyahsWqbf8A/ftmJLOY7+DmpOv7vL0fzuD1YbIwGHBbNHSWCHQuuS+zKlLUFLtRlv7XWmBfTZ/hxDqMvb6venZ4C718WXuIEw+QLLsd4qZcFXSRHV+ADkaDHuIPxPhEBCj8uyH8rmesDk61/Ckx0sjv66We+M6fXhPLiZWwKocJxbdV2E/o+qH8O1UtnGZxFKwKDNaNFWaghhvq3D8GiIvdXUjEihfAFbBhP6R7ZAmRh7qrVS9r62Jjffb9nnzx7KlNzAKFldchM9o23xnTCkJDRWZe0d/IGNkD83pt0XlFV9dYU+5nTysrEEpKVuywcAjvPIp7B5Tw+FavuK/CzQADuU5Bg4dC/tw="
    - secure: "Ndee8XVN4KDGocshbFavzGzBZ7RE8GW+hW+ECYRjuRsZXkxT2Q0zScEqQUX1aHwSSXfjSiB2Wcg/jkPhELWLT7mm8+mCg9+yWOXaowet/y2c8dBrBf6z4VcH6tYNs3xU6mKLIqofdI1SQpMAZto3B54BLNocHZ8FzgAJf+E8Ug8cysTDbG9Xs3pnUAueFAbRb8DYgqQQJG1i8NnV/zNTHmfPlapEv8P9EnAUwp5O0e0QvFqz3WiaigmVFM73yVxQWqbQo/8nDkfq9kb8KgNqBHdTBy7jX50TU112HjUrvG5+R6HDi/w492fINZfyNwrqtYkJYp3X1VNqyIPrApS67bnZ5LstP7bViAgmtUbBW1qYhPzc/g0M5lIbYlAJSMpEwdI4AHpHy71bv3WGe0NjDRttITGjC4GljaxbdSSmc+uGvppE/Jq/ev6AX84JCc3JlCRWIGdFbLI//ogFMFSPqA0Yd82dDM9gxfgyXNm43pqtlmCcIyhtNmGRDiD1L1bpwlsByQPP7Z4QQhrXGD6EQMIzUobbwpT4A2tFZ+BFKjxbvGp2fGd4a4MGscou1rtyfvhyIME37Vildm8slfpMwGrdwdUSU3YzPdYKvFrMX67C3eMcay72t8Xvko7oBVHwaLMhsS3yZcPm+jPlkGQliKBM3QBQGOXMz1+LQ8zPnqk="
